name: test

on:
  push:
  pull_request:

jobs:
  shell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install test dependencies
        run: sudo apt-get update && sudo apt-get install -y nftables shellcheck iproute2
      - name: Run isolated tests
        run: sudo ./tests/test.sh